### ISSUE TITLE
Missing slash

### ISSUE THREAD

**Issue by DavideBrex** [dfernandezperez/ChIPseq-snakemake#5]
Hi @dfernandezperez ,
I spotted what I believe is a small mistake. 
If in the config file you set trimming to true you will get this error: 

> InputFunctionException in line 32 of /shares/CIBIO-Storage/GROUPS/sharedLC/Davide/Chip-seq/ChIPseq-snakemake-master-PE/workflow/rules/trim.smk:
>   Error:
>   KeyError: 'trimmedA1A-DMSO-30gg-K27me3'
>  Wildcards:
>   sample=trimmedA1A-DMSO-30gg-K27me3

If trimming is set to false the error does not occur. The problem is in the common rules files I believe. You forgot a slash, see here:
https://github.com/dfernandezperez/ChIPseq-snakemake/blob/02771385ab68fcaba3e61e4b32519553d009c9e3/workflow/rules/common.smk#L31-L33

If you change `{tmp}/fastq/trimmed{sample}.{group}.fastq.gz` to `{tmp}/fastq/trimmed/{sample}.{group}.fastq.gz`then it works.

Thanks one more time for the nice pipeline!
Davide

**Comment by dfernandezperez** [comment]
Hey Davide!

Thanks a lot, I have already fixed the issue and pushed the update. We don't use anymore the trimming so I didn't catch the error, thanks again!

Daniel
